name: nix-flake-check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          # speeds up channels; you already pin nixpkgs via flake.lock
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Cachix
        uses: cachix/cachix-action@v14
        with:
          name: devnixosconfig                       # <-- change me
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
          # Optional, only needed if you want CI to PUSH to Cachix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run deadnix (fail on unused)
        run: nix run nixpkgs#deadnix -- -f

      - name: Run statix (lint)
        run: nix run nixpkgs#statix -- check .

      - name: Nix flake check
        run: nix flake check --show-trace

      - name: Build WSL system (smoke build)
        run: nix build .#nixosConfigurations.nixos.config.system.build.toplevel --print-build-logs

